# Gitleaks configuration for airbolt project

# Global allow list for test patterns
[allowlist]
description = "Global allow list for test files and examples"

# Allow test files that contain example API keys
paths = [
  '''test/.*\.test\.ts$''',
  '''test/.*\.test\.js$''',
  '''__tests__/.*\.ts$''',
  '''__tests__/.*\.js$''',
  '''\.test\.ts$''',
  '''\.test\.js$''',
  '''examples/.*''',
  '''docs/.*\.md$'''
]

# Additional patterns to ignore in test contexts
regexes = [
  '''sk-test[A-Za-z0-9_-]+''',
  '''sk-example[A-Za-z0-9_-]+''',
  '''sk-demo[A-Za-z0-9_-]+''',
  '''sk-mock[A-Za-z0-9_-]+'''
]

# Custom rule to ensure we still catch real keys
[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[A-Za-z0-9]{48}'''
tags = ["key", "openai"]