services:
  - type: web
    name: airbolt
    runtime: node
    plan: free
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm exec nx run backend-api:build
    startCommand: node apps/backend-api/dist/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: AI_PROVIDER
        value: openai # Default to OpenAI, can be changed to 'anthropic'
      - key: OPENAI_API_KEY
        sync: false # Prompts user to enter value during deployment if using OpenAI
      - key: ANTHROPIC_API_KEY
        sync: false # Prompts user to enter value during deployment if using Anthropic
      - key: JWT_SECRET
        generateValue: true # Render generates a secure random value
      - key: ALLOWED_ORIGIN
        value: '*' # Allow all origins for SDK deployment model
      - key: TRUST_PROXY
        value: 'true'
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_MAX
        value: '100'
      - key: RATE_LIMIT_TIME_WINDOW
        value: '60000'
