name: Documentation Link Check

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - '.markdown-link-check.json'
      - 'scripts/check-links.js'
      - '.github/workflows/docs-link-check.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.md'
      - '.markdown-link-check.json'
      - 'scripts/check-links.js'
      - '.github/workflows/docs-link-check.yml'

jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm add -g markdown-link-check

      - name: Check documentation links
        run: |
          node scripts/check-links.js --verbose
        env:
          # Prevent rate limiting issues
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Report results
        if: failure()
        run: |
          echo "❌ Documentation link check failed"
          echo "Some links in the documentation are broken."
          echo "Please run 'pnpm docs:check-links:verbose' locally to see detailed errors."
          exit 1
