name: SDK Generation

on:
  push:
    branches: [main]
    paths:
      - 'apps/backend-api/src/**'
      - 'fern/**'
      - '.github/workflows/sdk-generation.yml'
  workflow_dispatch:

concurrency:
  group: sdk-generation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-sdk:
    name: Generate SDK
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Generate OpenAPI specification
        run: pnpm openapi:generate

      - name: Validate SDK is up-to-date
        run: |
          # Generate SDK
          pnpm sdk:generate
          
          # Check if there are changes
          if ! git diff --quiet HEAD -- packages/sdk/generated; then
            echo "❌ Generated SDK is out of date!"
            echo "Please run 'pnpm sdk:generate' and commit the changes"
            git diff --name-status packages/sdk/generated
            exit 1
          fi
          
          echo "✅ SDK is up-to-date"